### ISSUE TITLE
Add contribution, bounty, proposal policy

### ISSUE THREAD

**Issue by emergent-reasons** [flipstarter/flipstarter.cash#20]
Will propose content in the flipstarter repo and I figure we can link to it from the site.

**Comment by merc1er** [comment]
I offer to implement this with the content of https://gitlab.com/flipstarter/flipstarter-electron-cash/-/merge_requests/45/diffs (in `README.md`).

I propose $200 for this work.

**Comment by emergent-reasons** [comment]
FYI changed content of guideline based on your feedback. Pending merge on those two.

**Comment by emergent-reasons** [comment]
Ok @merc1er the improvements are merged in both campaign and plugin repositories. I think you are good to go if we can get one more contributor to confirm.

**Comment by merc1er** [comment]
> Ok @merc1er the improvements are merged in both campaign and plugin repositories. I think you are good to go if we can get one more contributor to confirm.

Ok, I will start working on this whenever you give me green light.

**Comment by emergent-reasons** [comment]
Got another confirmation. Feel free to go for it
