### ISSUE TITLE
Flipstarter says to look at site for cancelling instructions but there aren't any there

### ISSUE THREAD

**Issue by emergent-reasons** [flipstarter/flipstarter.cash#9]
This is because it previously pointed to a readcash article which has links.

#1 covers the articles in general but at least we need to meet this expectation that Flipstarter gives about canceling:

> Flipstarter pledge. To cancel, see FAQ at flipstarter.cash

**Comment by merc1er** [comment]
I can add a tutorial for pledging and cancelling pledges (probably by re-using [this article](https://read.cash/@flipstarter/how-to-support-a-flipstarter-campaign-f27240d9)).

Proposed price is $100 in BCH.

**Comment by monsterbitar** [comment]
I'm fine with this.

**Comment by emergent-reasons** [comment]
Me too. Go for it @merc1er

**Comment by emergent-reasons** [comment]
We have the Chinese version also if you reuse the text.
